name: Build and Deploy code
on: [push, pull_request]
jobs:
    build:
        environment:
            name: testing
        env:
            DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
            DATABASE_PORT: ${{secrets.DATABASE_PORT}}
            DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
            DATABASE_NAME: ${{secrets.DATABASE_NAME}}
            DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
            ALGORITHM: ${{secrets.ALGORITHM}}
            SECRET_KEY: ${{secrets.SECRET_KEY}}
            ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
            TEST_DATABASE_NAME: ${{vars.TEST_DATABASE_NAME}}
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
                    POSTGRES_DB: ${{vars.TEST_DATABASE_NAME}}
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        runs-on: ubuntu-22.04
        steps:
            - name: pulling git repo
              uses: actions/checkout@v4
            - name: install python version > 3.10
              uses: actions/setup-python@v5
              with:
                python-version: '>=3.10 <=3.12'
            - name: update pip
              run: python -m pip install --upgrade pip
            - name: install all dependencies
              run: pip install -r requirements.txt
            #- name: add tables with alembic
            #  run: alembic upgrade head
            - name: test with pytest
              run: pytest